# Generated by Django 3.2.6 on 2021-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210808_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
