# Generated by Django 3.2.6 on 2021-08-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(default='652E8A767D', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
