# Generated by Django 3.2.6 on 2021-08-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
